# Site
title:              Nhạ Nguyễn
bio:                'A developer has an artistic soul'
description:        "Code for food."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://nhanv.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            NullPhilips
facebook:           phac.nam
github:             nhanv
stackoverflow:      4736587/philips-null
#linkedin:          https://www.linkedin.com/in/nh%E1%BA%A1-nguy%E1%BB%85n-a36520117?trk=nav_responsive_tab_profile_pic
#xing:              username
#instagram:         https://www.flickr.com/photos/134924531@N05/
#https://www.instagram.com/philipsnull/
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:             https://steamcommunity.com/profiles/76561198326655734/home
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
flickr:             134924531@N05
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
